</$objtype/mkfile

TARG = rna

BIN = /$objtype/bin/rosalind

OFILES = main.$O \

HFILES = #unused

</sys/src/cmd/mkone

demo:V: all
	# Expecting output: GAUGGAACUUGACUACGUAAAUU
	echo -n GATGGAACTTGACTACGTAAATT | $O.out
	echo
